import CarDetailClient from './CarDetailClient';

export interface CarPerformanceReport {
  accidentHistory: string;
  floodDamage: string;
  totalLoss: string;
  usageChange: string;
  odometerStatus: string;
  overallGrade: string;
  exteriorCondition: string;
  interiorCondition: string;
  engineCondition: string;
  transmissionCondition: string;
  steeringCondition: string;
  brakeCondition: string;
  electricalCondition: string;
  tireCondition: string;
  paintStatus: {
    hood: string;
    frontLeftFender: string;
    frontRightFender: string;
    frontLeftDoor: string;
    frontRightDoor: string;
    rearLeftDoor: string;
    rearRightDoor: string;
    rearLeftFender: string;
    rearRightFender: string;
    trunk: string;
    roof: string;
  };
}

export interface CarOption {
  name: string;
  available: boolean;
}

export interface CarData {
  id: number;
  brand: string;
  model: string;
  year: number;
  mileage: number;
  price: number;
  fuel: string;
  transmission: string;
  bodyType: string;
  color: string;
  engine: string;
  displacement: string;
  drivetrain: string;
  doors: number;
  seats: number;
  vin: string;
  plateNumber: string;
  firstRegistration: string;
  description: string;
  images: string[];
  status: string;
  options: CarOption[];
  performanceReport: CarPerformanceReport;
}

const carsData: Record<string, CarData> = {
  '1': {
    id: 1,
    brand: 'Hyundai',
    model: 'Sonata DN8',
    year: 2023,
    mileage: 15000,
    price: 28500,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Phantom Black',
    engine: '2.5L Smartstream',
    displacement: '2,497 cc',
    drivetrain: 'Front-Wheel Drive',
    doors: 4,
    seats: 5,
    vin: 'KMHL341CBNA123456',
    plateNumber: '123가 4567',
    firstRegistration: '2023-03-15',
    description: 'This 2023 Hyundai Sonata DN8 is in excellent condition with low mileage. Thoroughly inspected and ready for export.',
    images: [
      'https://images.unsplash.com/photo-1590656371803-0ae2ae004989?w=1200',
      'https://images.unsplash.com/photo-1688893287874-ac7fbd686c24?w=1200',
      'https://images.unsplash.com/photo-1714348938045-0c74379cd4d9?w=1200',
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Sunroof', available: true },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: true },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: false },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: false },
      { name: 'Head-Up Display', available: false },
      { name: 'Bose Premium Audio', available: true },
      { name: 'Dash Camera', available: false },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A',
      exteriorCondition: 'Good',
      interiorCondition: 'Excellent',
      engineCondition: 'Excellent',
      transmissionCondition: 'Excellent',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Excellent',
      tireCondition: 'Good (70% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '2': {
    id: 2,
    brand: 'Kia',
    model: 'K5 DL3',
    year: 2022,
    mileage: 28000,
    price: 24500,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Snow White Pearl',
    engine: '2.5L GDi',
    displacement: '2,497 cc',
    drivetrain: 'Front-Wheel Drive',
    doors: 4,
    seats: 5,
    vin: 'KNAG411ABNA654321',
    plateNumber: '456나 7890',
    firstRegistration: '2022-06-20',
    description: '2022 Kia K5 DL3 in excellent condition. Ready for export with all documentation.',
    images: [
      'https://images.unsplash.com/photo-1688893287874-ac7fbd686c24?w=1200',
      'https://images.unsplash.com/photo-1590656371803-0ae2ae004989?w=1200',
      'https://images.unsplash.com/photo-1714348938045-0c74379cd4d9?w=1200',
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Sunroof', available: false },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: false },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: false },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: false },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: false },
      { name: 'Head-Up Display', available: false },
      { name: 'Bose Premium Audio', available: false },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A',
      exteriorCondition: 'Good',
      interiorCondition: 'Good',
      engineCondition: 'Excellent',
      transmissionCondition: 'Good',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Good',
      tireCondition: 'Good (60% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Repainted',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '3': {
    id: 3,
    brand: 'Genesis',
    model: 'G80 RG3',
    year: 2023,
    mileage: 12000,
    price: 52000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Vik Black',
    engine: '3.5L Twin-Turbo V6',
    displacement: '3,470 cc',
    drivetrain: 'All-Wheel Drive',
    doors: 4,
    seats: 5,
    vin: 'KMTG541DBPA789012',
    plateNumber: '789다 1234',
    firstRegistration: '2023-01-10',
    description: 'Luxury 2023 Genesis G80 with premium features. Exceptional luxury sedan ready for export.',
    images: [
      'https://images.unsplash.com/photo-1714348938045-0c74379cd4d9?w=1200',
      'https://images.unsplash.com/photo-1590656371803-0ae2ae004989?w=1200',
      'https://images.unsplash.com/photo-1688893287874-ac7fbd686c24?w=1200',
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Panoramic Sunroof', available: true },
      { name: 'Nappa Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: true },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: true },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: true },
      { name: 'Head-Up Display', available: true },
      { name: 'Lexicon Premium Audio', available: true },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A+',
      exteriorCondition: 'Excellent',
      interiorCondition: 'Excellent',
      engineCondition: 'Excellent',
      transmissionCondition: 'Excellent',
      steeringCondition: 'Excellent',
      brakeCondition: 'Excellent',
      electricalCondition: 'Excellent',
      tireCondition: 'Excellent (85% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '4': {
    id: 4,
    brand: 'Hyundai',
    model: 'Tucson NX4',
    year: 2022,
    mileage: 32000,
    price: 31000,
    fuel: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Amazon Gray',
    engine: '2.0L CRDi',
    displacement: '1,997 cc',
    drivetrain: 'All-Wheel Drive',
    doors: 4,
    seats: 5,
    vin: 'KMHJ381CDNA234567',
    plateNumber: '234라 5678',
    firstRegistration: '2022-05-10',
    description: '2022 Hyundai Tucson NX4 diesel AWD in great condition. Spacious SUV with advanced safety features, perfect for families.',
    images: [
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
      'https://images.unsplash.com/photo-1590656371803-0ae2ae004989?w=1200',
      'https://images.unsplash.com/photo-1688893287848-a218df183f36?w=1200',
      'https://images.unsplash.com/photo-1575764679429-57558f46f259?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Sunroof', available: true },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: false },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: false },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: true },
      { name: 'Head-Up Display', available: false },
      { name: 'Bose Premium Audio', available: false },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A',
      exteriorCondition: 'Good',
      interiorCondition: 'Good',
      engineCondition: 'Good',
      transmissionCondition: 'Good',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Good',
      tireCondition: 'Good (55% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Repainted',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '5': {
    id: 5,
    brand: 'Kia',
    model: 'Sorento MQ4',
    year: 2023,
    mileage: 18000,
    price: 38000,
    fuel: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Snow White Pearl',
    engine: '2.2L CRDi Smartstream',
    displacement: '2,151 cc',
    drivetrain: 'All-Wheel Drive',
    doors: 4,
    seats: 7,
    vin: 'KNAS511ABPA345678',
    plateNumber: '345마 6789',
    firstRegistration: '2023-02-25',
    description: '2023 Kia Sorento MQ4 with 7 seats and diesel AWD. Low mileage, full option package with advanced ADAS features.',
    images: [
      'https://images.unsplash.com/photo-1688893287848-a218df183f36?w=1200',
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
      'https://images.unsplash.com/photo-1575764679429-57558f46f259?w=1200',
      'https://images.unsplash.com/photo-1714348938323-534552cbfad9?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Panoramic Sunroof', available: true },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: true },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: true },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: true },
      { name: 'Head-Up Display', available: false },
      { name: 'Bose Premium Audio', available: true },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A',
      exteriorCondition: 'Good',
      interiorCondition: 'Excellent',
      engineCondition: 'Excellent',
      transmissionCondition: 'Excellent',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Excellent',
      tireCondition: 'Good (75% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '6': {
    id: 6,
    brand: 'Hyundai',
    model: 'Palisade LX2',
    year: 2022,
    mileage: 25000,
    price: 45000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Abyss Black Pearl',
    engine: '3.8L V6 GDi',
    displacement: '3,778 cc',
    drivetrain: 'All-Wheel Drive',
    doors: 4,
    seats: 8,
    vin: 'KMHR381DBNA456789',
    plateNumber: '456바 7890',
    firstRegistration: '2022-08-12',
    description: 'Flagship 2022 Hyundai Palisade LX2 with 8-seat configuration. Premium features throughout, ideal for large families or VIP transport.',
    images: [
      'https://images.unsplash.com/photo-1575764679429-57558f46f259?w=1200',
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
      'https://images.unsplash.com/photo-1688893287848-a218df183f36?w=1200',
      'https://images.unsplash.com/photo-1714348938323-534552cbfad9?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Sunroof', available: true },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: true },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: true },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: true },
      { name: 'Head-Up Display', available: true },
      { name: 'JBL Premium Audio', available: true },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A',
      exteriorCondition: 'Good',
      interiorCondition: 'Good',
      engineCondition: 'Good',
      transmissionCondition: 'Good',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Good',
      tireCondition: 'Good (65% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Repainted',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '7': {
    id: 7,
    brand: 'Genesis',
    model: 'GV80',
    year: 2023,
    mileage: 8000,
    price: 65000,
    fuel: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Cardiff Green',
    engine: '3.0L Inline-6 Turbo Diesel',
    displacement: '2,996 cc',
    drivetrain: 'All-Wheel Drive',
    doors: 4,
    seats: 5,
    vin: 'KMUG581EBPA567890',
    plateNumber: '567사 8901',
    firstRegistration: '2023-04-05',
    description: 'Premium 2023 Genesis GV80 luxury SUV with only 8,000 km. Full luxury package with Lexicon audio and advanced driving aids.',
    images: [
      'https://images.unsplash.com/photo-1714348938323-534552cbfad9?w=1200',
      'https://images.unsplash.com/photo-1575764679429-57558f46f259?w=1200',
      'https://images.unsplash.com/photo-1714348938045-0c74379cd4d9?w=1200',
      'https://images.unsplash.com/photo-1688893287848-a218df183f36?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Panoramic Sunroof', available: true },
      { name: 'Nappa Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: true },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: true },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: true },
      { name: 'Head-Up Display', available: true },
      { name: 'Lexicon Premium Audio', available: true },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A+',
      exteriorCondition: 'Excellent',
      interiorCondition: 'Excellent',
      engineCondition: 'Excellent',
      transmissionCondition: 'Excellent',
      steeringCondition: 'Excellent',
      brakeCondition: 'Excellent',
      electricalCondition: 'Excellent',
      tireCondition: 'Excellent (90% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '8': {
    id: 8,
    brand: 'Kia',
    model: 'Carnival KA4',
    year: 2022,
    mileage: 35000,
    price: 42000,
    fuel: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'Van',
    color: 'Snow White Pearl',
    engine: '2.2L CRDi Smartstream',
    displacement: '2,151 cc',
    drivetrain: 'Front-Wheel Drive',
    doors: 5,
    seats: 11,
    vin: 'KNAK811CBNA678901',
    plateNumber: '678아 9012',
    firstRegistration: '2022-04-18',
    description: '2022 Kia Carnival KA4 with 11-seat configuration. Ideal for passenger transport or large family use. Well-maintained with full service history.',
    images: [
      'https://images.unsplash.com/photo-1592805723127-004b174a1798?w=1200',
      'https://images.unsplash.com/photo-1665564593840-f20a27db050a?w=1200',
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
      'https://images.unsplash.com/photo-1688893287848-a218df183f36?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Sunroof', available: false },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats (1st & 2nd Row)', available: true },
      { name: 'Ventilated Seats', available: false },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: false },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: false },
      { name: 'LED Headlights', available: true },
      { name: 'Power Sliding Doors', available: true },
      { name: 'Power Trunk', available: true },
      { name: 'Rear Entertainment System', available: false },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'B+',
      exteriorCondition: 'Good',
      interiorCondition: 'Fair',
      engineCondition: 'Good',
      transmissionCondition: 'Good',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Good',
      tireCondition: 'Fair (45% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Repainted',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Repainted',
        roof: 'Normal',
      },
    },
  },
  '9': {
    id: 9,
    brand: 'Hyundai',
    model: 'Staria',
    year: 2023,
    mileage: 12000,
    price: 48000,
    fuel: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'Van',
    color: 'Moonlight Blue',
    engine: '2.2L CRDi',
    displacement: '2,199 cc',
    drivetrain: 'Front-Wheel Drive',
    doors: 5,
    seats: 9,
    vin: 'KMJW911DBPA789012',
    plateNumber: '789자 0123',
    firstRegistration: '2023-01-22',
    description: '2023 Hyundai Staria Premium with futuristic design. Low mileage, 9-seat luxury MPV with spacious cabin and modern safety features.',
    images: [
      'https://images.unsplash.com/photo-1665564593840-f20a27db050a?w=1200',
      'https://images.unsplash.com/photo-1592805723127-004b174a1798?w=1200',
      'https://images.unsplash.com/photo-1575764679429-57558f46f259?w=1200',
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Sunroof', available: false },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: true },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: true },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Sliding Doors', available: true },
      { name: 'Power Trunk', available: true },
      { name: 'Rear Entertainment System', available: true },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A',
      exteriorCondition: 'Excellent',
      interiorCondition: 'Excellent',
      engineCondition: 'Excellent',
      transmissionCondition: 'Excellent',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Excellent',
      tireCondition: 'Good (80% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '10': {
    id: 10,
    brand: 'Hyundai',
    model: 'Avante CN7',
    year: 2021,
    mileage: 45000,
    price: 18000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Intense Blue',
    engine: '1.6L Smartstream',
    displacement: '1,598 cc',
    drivetrain: 'Front-Wheel Drive',
    doors: 4,
    seats: 5,
    vin: 'KMHD041ABMA890123',
    plateNumber: '890차 1234',
    firstRegistration: '2021-09-08',
    description: '2021 Hyundai Avante CN7 with competitive price point. Well-maintained sedan with good fuel efficiency, ideal for daily commuting.',
    images: [
      'https://images.unsplash.com/photo-1665564591116-19a1d2cdb0cc?w=1200',
      'https://images.unsplash.com/photo-1590656371803-0ae2ae004989?w=1200',
      'https://images.unsplash.com/photo-1688893287874-ac7fbd686c24?w=1200',
      'https://images.unsplash.com/photo-1714348938517-ebe870af89c1?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Sunroof', available: false },
      { name: 'Leather Seats', available: false },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: false },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: false },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: false },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: false },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: false },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: false },
      { name: 'Head-Up Display', available: false },
      { name: 'Premium Audio', available: false },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'Minor (Rear bumper)',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'B+',
      exteriorCondition: 'Fair',
      interiorCondition: 'Good',
      engineCondition: 'Good',
      transmissionCondition: 'Good',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Good',
      tireCondition: 'Fair (40% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Repainted',
        roof: 'Normal',
      },
    },
  },
  '11': {
    id: 11,
    brand: 'Kia',
    model: 'Sportage NQ5',
    year: 2023,
    mileage: 10000,
    price: 32000,
    fuel: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Expedition Green',
    engine: '1.6L T-GDi Hybrid',
    displacement: '1,598 cc',
    drivetrain: 'All-Wheel Drive',
    doors: 4,
    seats: 5,
    vin: 'KNAS211DBPA901234',
    plateNumber: '901카 2345',
    firstRegistration: '2023-05-30',
    description: '2023 Kia Sportage NQ5 Hybrid AWD with exceptional fuel economy. Very low mileage, modern design with full safety suite.',
    images: [
      'https://images.unsplash.com/photo-1710594022719-a37944dc12ae?w=1200',
      'https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=1200',
      'https://images.unsplash.com/photo-1688893287848-a218df183f36?w=1200',
      'https://images.unsplash.com/photo-1575764679429-57558f46f259?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Panoramic Sunroof', available: true },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: true },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: true },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: true },
      { name: 'Head-Up Display', available: true },
      { name: 'Harman Kardon Audio', available: true },
      { name: 'Dash Camera', available: true },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A+',
      exteriorCondition: 'Excellent',
      interiorCondition: 'Excellent',
      engineCondition: 'Excellent',
      transmissionCondition: 'Excellent',
      steeringCondition: 'Excellent',
      brakeCondition: 'Excellent',
      electricalCondition: 'Excellent',
      tireCondition: 'Excellent (90% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Normal',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
  '12': {
    id: 12,
    brand: 'Genesis',
    model: 'G70',
    year: 2022,
    mileage: 22000,
    price: 42000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Havana Red',
    engine: '2.0L Turbo GDi',
    displacement: '1,998 cc',
    drivetrain: 'Rear-Wheel Drive',
    doors: 4,
    seats: 5,
    vin: 'KMTG341CBNA012345',
    plateNumber: '012타 3456',
    firstRegistration: '2022-07-14',
    description: '2022 Genesis G70 sport sedan with rear-wheel drive. Engaging driving dynamics combined with luxury comfort. Well-equipped and export ready.',
    images: [
      'https://images.unsplash.com/photo-1714348938517-ebe870af89c1?w=1200',
      'https://images.unsplash.com/photo-1714348938045-0c74379cd4d9?w=1200',
      'https://images.unsplash.com/photo-1590656371803-0ae2ae004989?w=1200',
      'https://images.unsplash.com/photo-1688893287874-ac7fbd686c24?w=1200',
    ],
    status: 'available',
    options: [
      { name: 'Navigation', available: true },
      { name: 'Sunroof', available: true },
      { name: 'Leather Seats', available: true },
      { name: 'Heated Seats', available: true },
      { name: 'Ventilated Seats', available: true },
      { name: 'Heated Steering Wheel', available: true },
      { name: 'Smart Cruise Control', available: true },
      { name: 'Lane Keeping Assist', available: true },
      { name: 'Blind Spot Monitor', available: true },
      { name: 'Forward Collision Avoidance', available: true },
      { name: 'Rear Camera', available: true },
      { name: 'Around View Monitor', available: false },
      { name: 'Parking Sensors', available: true },
      { name: 'Apple CarPlay / Android Auto', available: true },
      { name: 'Wireless Charging', available: true },
      { name: 'LED Headlights', available: true },
      { name: 'Power Trunk', available: false },
      { name: 'Head-Up Display', available: true },
      { name: 'Lexicon Premium Audio', available: true },
      { name: 'Dash Camera', available: false },
    ],
    performanceReport: {
      accidentHistory: 'None',
      floodDamage: 'None',
      totalLoss: 'None',
      usageChange: 'None',
      odometerStatus: 'Normal',
      overallGrade: 'A',
      exteriorCondition: 'Good',
      interiorCondition: 'Good',
      engineCondition: 'Excellent',
      transmissionCondition: 'Excellent',
      steeringCondition: 'Good',
      brakeCondition: 'Good',
      electricalCondition: 'Excellent',
      tireCondition: 'Good (60% remaining)',
      paintStatus: {
        hood: 'Normal',
        frontLeftFender: 'Repainted',
        frontRightFender: 'Normal',
        frontLeftDoor: 'Normal',
        frontRightDoor: 'Normal',
        rearLeftDoor: 'Normal',
        rearRightDoor: 'Normal',
        rearLeftFender: 'Normal',
        rearRightFender: 'Normal',
        trunk: 'Normal',
        roof: 'Normal',
      },
    },
  },
};

const allCarsForRelated = [
  { id: 1, brand: 'Hyundai', model: 'Sonata DN8', year: 2023, mileage: 15000, price: 28500, fuel: 'Gasoline', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1590656371803-0ae2ae004989?w=800'] },
  { id: 2, brand: 'Kia', model: 'K5 DL3', year: 2022, mileage: 28000, price: 24500, fuel: 'Gasoline', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1688893287874-ac7fbd686c24?w=800'] },
  { id: 3, brand: 'Genesis', model: 'G80 RG3', year: 2023, mileage: 12000, price: 52000, fuel: 'Gasoline', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1714348938045-0c74379cd4d9?w=800'] },
  { id: 4, brand: 'Hyundai', model: 'Tucson NX4', year: 2022, mileage: 32000, price: 31000, fuel: 'Diesel', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1616627091698-50d033ce0980?w=800'] },
  { id: 5, brand: 'Kia', model: 'Sorento MQ4', year: 2023, mileage: 18000, price: 38000, fuel: 'Diesel', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1688893287848-a218df183f36?w=800'] },
  { id: 6, brand: 'Hyundai', model: 'Palisade LX2', year: 2022, mileage: 25000, price: 45000, fuel: 'Gasoline', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1575764679429-57558f46f259?w=800'] },
  { id: 7, brand: 'Genesis', model: 'GV80', year: 2023, mileage: 8000, price: 65000, fuel: 'Diesel', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1714348938323-534552cbfad9?w=800'] },
  { id: 8, brand: 'Kia', model: 'Carnival KA4', year: 2022, mileage: 35000, price: 42000, fuel: 'Diesel', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800'] },
  { id: 9, brand: 'Hyundai', model: 'Staria', year: 2023, mileage: 12000, price: 48000, fuel: 'Diesel', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1665564593840-f20a27db050a?w=800'] },
  { id: 10, brand: 'Hyundai', model: 'Avante CN7', year: 2021, mileage: 45000, price: 18000, fuel: 'Gasoline', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1665564591116-19a1d2cdb0cc?w=800'] },
  { id: 11, brand: 'Kia', model: 'Sportage NQ5', year: 2023, mileage: 10000, price: 32000, fuel: 'Hybrid', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1710594022719-a37944dc12ae?w=800'] },
  { id: 12, brand: 'Genesis', model: 'G70', year: 2022, mileage: 22000, price: 42000, fuel: 'Gasoline', transmission: 'Automatic', images: ['https://images.unsplash.com/photo-1714348938517-ebe870af89c1?w=800'] },
];

export function generateStaticParams() {
  return Object.keys(carsData).map((id) => ({
    id: id,
  }));
}

export default async function CarDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const car = carsData[id] || carsData['1'];

  // Show up to 3 related cars from the same brand or body type, excluding current
  const related = allCarsForRelated
    .filter((c) => c.id !== car.id)
    .filter((c) => c.brand === car.brand || carsData[c.id.toString()]?.bodyType === car.bodyType)
    .slice(0, 3);

  // If not enough related, fill with other cars
  const finalRelated = related.length >= 3
    ? related
    : [
        ...related,
        ...allCarsForRelated
          .filter((c) => c.id !== car.id && !related.find((r) => r.id === c.id))
          .slice(0, 3 - related.length),
      ];

  return <CarDetailClient car={car} relatedCars={finalRelated} />;
}
